In [13]:
url = 'https://www.basketball-reference.com/leagues/NBA_2023_standings.html#all_confs_standings_E'

In [14]:
import requests

data = requests.get(url)

with open("stats.html", "w+") as f:
        f.write(data.text)

In [15]:
from bs4 import BeautifulSoup

In [17]:
with open("stats.html") as f:
    page = f.read()
    
soup = BeautifulSoup(page, 'html.parser')

In [42]:
confs_standings_E = soup.find(id='confs_standings_E')
confs_standings_W = soup.find(id='confs_standings_W')

In [22]:
import pandas as pd

In [51]:
confs_standings = pd.read_html(str(confs_standings_E) + str(confs_standings_W))
#confs_standings_W = pd.read_html(str(confs_standings_W))

In [61]:
df_E = confs_standings[0]
df_W = confs_standings[1]
df_E.rename({'Eastern Conference': 'Team'}, axis=1, inplace=True)
df_W.rename({'Western Conference': 'Team'}, axis=1, inplace=True)

In [159]:
df_all = pd.concat([df_E, df_W], axis=0)
df_all.reset_index(drop=True, inplace=True)
df_all

                          Team  W  L  W/L%   GB   PS/G   PA/G  SRS
0           Boston Celtics (1)  1  0   1.0    —  126.0  117.0  3.5
1       Washington Wizards (1)  1  0   1.0    —  114.0  107.0  0.0
2          Toronto Raptors (1)  1  0   1.0    —  108.0  105.0  0.0
3          Milwaukee Bucks (1)  1  0   1.0    —   90.0   88.0 -3.5
4          Detroit Pistons (1)  1  0   1.0    —  113.0  109.0  0.0
5            Atlanta Hawks (1)  1  0   1.0    —  117.0  107.0  0.0
6        Charlotte Hornets (1)  1  0   1.0    —  129.0  102.0  0.0
7            Chicago Bulls (1)  1  0   1.0    —  116.0  108.0  0.0
8            Brooklyn Nets (9)  0  1   0.0  1.0  108.0  130.0  0.0
9           Indiana Pacers (9)  0  1   0.0  1.0  107.0  114.0  0.0
10           Orlando Magic (9)  0  1   0.0  1.0  109.0  113.0  0.0
11              Miami Heat (9)  0  1   0.0  1.0  108.0  116.0  0.0
12     Cleveland Cavaliers (9)  0  1   0.0  1.0  105.0  108.0  0.0
13         New York Knicks (9)  0  1   0.0  1.0  112.0  115.0  0.0
14      Philadelphia 76ers (9)  0  2   0.0  1.5  102.5  108.0  0.0
15  Minnesota Timberwolves (1)  1  0   1.0    —  115.0  108.0  0.0
16               Utah Jazz (1)  1  0   1.0    —  123.0  102.0  0.0
17  Portland Trail Blazers (1)  1  0   1.0    —  115.0  108.0  0.0
18            Phoenix Suns (1)  1  0   1.0    —  107.0  105.0  0.0
19    New Orleans Pelicans (1)  1  0   1.0    —  130.0  108.0  0.0
20       Memphis Grizzlies (1)  1  0   1.0    —  115.0  112.0  0.0
21    Los Angeles Clippers (1)  1  0   1.0    —  103.0   97.0 -4.0
22   Golden State Warriors (1)  1  0   1.0    —  123.0  109.0  4.0
23   Oklahoma City Thunder (9)  0  1   0.0  1.0  108.0  115.0  0.0
24         Houston Rockets (9)  0  1   0.0  1.0  107.0  117.0  0.0
25        Sacramento Kings (9)  0  1   0.0  1.0  108.0  115.0  0.0
26       San Antonio Spurs (9)  0  1   0.0  1.0  102.0  129.0  0.0
27          Denver Nuggets (9)  0  1   0.0  1.0  102.0  123.0  0.0
28        Dallas Mavericks (9)  0  1   0.0  1.0  105.0  107.0  0.0
29      Los Angeles Lakers (9)  0  2   0.0  1.5  103.0  113.0  0.0

In [160]:
#df_all.loc[df_all.Team == 'Boston Celtics  (1)']
df_all['Team'] = df_all['Team'].str.split()

In [162]:
#del df_all['Team'][29][-1]
df_all['Team'][0][-1]

'(1)'